@startuml
autonumber

title US1020 - Send Email to Candidate

participant ":EventPublisher" as EP <<application>>
participant ":ApplicationAccepted\nWatchDog" as WD <<application>>
participant ":SendEmailOnApplication\nAcceptedController" as CTRL_EVENT <<application>>
participant ":FollowUpConnectionService" as ENTITY


 -> EP : publish()
activate EP

EP -> WD: onEvent()
activate WD

WD -> CTRL_EVENT**: create()
activate CTRL_EVENT

note right
Upon creation of controller
a connection will be established
with the FollowUp server
end note

CTRL_EVENT -> ENTITY: connectToServer()
activate ENTITY

ENTITY --> CTRL_EVENT : success
deactivate ENTITY
deactivate CTRL_EVENT


WD -> CTRL_EVENT: sendEmail(applicationAcceptedEvent)
activate CTRL_EVENT

CTRL_EVENT -> ENTITY: sendEmail(customerManagerEmail,\ncandidateEmail, topic, emailBody)
activate ENTITY
deactivate ENTITY

deactivate WD
deactivate EP
deactivate CTRL_EVENT

@enduml


