@startuml
autonumber

title [US1001] Register Customer - 1

actor "Customer Manager" as USER

participant "RegisterCustomerUI" as UI <<presentation>>
participant "RegisterCustomerController" as CTRL <<controller>>
participant "GeneratePasswordService" as GPS <<service>>
participant "RandomPassword" as PG <<domain>>
participant "AuthorizationService" as AUTHZ <<service>>
participant "EntityManagementService" as EMS <<service>>
participant "EventPublisher" as EP <<domain>>
participant "UserManagementService" as UMS <<service>>
participant "NewCustomerUser\nRegisteredEvent" as EVENT <<domain>>




note right UMS
The UserManagementService and
AuthorizationService are implemented
in the eapli framework and will
be used in this functionality.
end note

activate USER

USER -> UI: wants to register new customer
activate UI

UI -> CTRL**: create



UI --> USER: asks for necessary information


USER -> UI: companyName, address, customerCode,\nuserEmail, userName, phoneNumber
UI -> CTRL: registerEntity(companyName, address, customerCode,\nuserEmail, userName, phoneNumber)
activate CTRL

CTRL -> GPS: generatePassword()
activate GPS

GPS -> PG**: create()
activate PG

PG --> GPS: password
deactivate PG

GPS --> CTRL: password
deactivate GPS

CTRL -> AUTHZ:  loggedinUserWithPermissions(roles)
activate AUTHZ

AUTHZ -> CTRL:  customerManagerUser
deactivate AUTHZ

CTRL -> EMS: registerNewEntity(companyName, address, customerCode,\ncustomerManagerUser)
activate EMS


EMS -> UMS: registerNewUser(email, password, name,  roles)
            activate UMS

UMS --> EMS: customerUser
deactivate UMS



EMS -> EVENT**: create(companyName, address, customerCode,\ncustomerManagerUser, customerUser)

EMS -> EP : publish(event)
activate EP

deactivate EP

deactivate EMS


deactivate CTRL


deactivate USER

@enduml
