@startuml US1002_partial_job_opening_attribute_list_to_DTO
'https://plantuml.com/sequence-diagram

title [US1002 - Partial SD] Job Opening Attribute List to DTO

control "<<application>>\n:RegisterJobOpeningController" as CTRL
participant "<<service>>\n:JobOpeningMapper" as JobOpMapper
participant "<<domain>>\n<<Value Object>>\n:WorkMode" as Work
participant "<<domain>>\n<<Value Object>>\n:ContractType" as Contract
participant "<<domain>>\n<<Entity>>\n:RequirementSpecification" as ReqSpe
participant "<<application>>\nList<JobOpeningDTO>" as DTOList
participant "<<application>>\nJobOpeningDTO" as DTO


-> CTRL : toDTO(className, list)

activate CTRL

    CTRL -> JobOpMapper : convertToDTO(className, list)
    activate JobOpMapper

        JobOpMapper -> DTOList : create()
        activate DTOList
        deactivate DTOList

        loop For all the elements in the list
            alt className = ContractType
                'loop for all contract types
                    JobOpMapper -> Contract : type()
                    activate Contract
                    deactivate Contract
                'end loop

            else className = WorkMode
                'loop for all work mode
                    JobOpMapper -> Work : mode()
                    activate Work
                    deactivate Work
                'end loop

            else className = RequirementsSpecifications
                'loop for all requirements specifications files
                    JobOpMapper -> ReqSpe : requirementsFileName()
                    activate ReqSpe
                    deactivate ReqSpe
                'end loop

            end alt

            JobOpMapper -> DTO : create(element)
            activate DTO
            deactivate DTO

            JobOpMapper -> DTOList : add(elementDTO)
            activate DTOList
            deactivate DTOList
        end loop

        JobOpMapper --> CTRL

    deactivate JobOpMapper

<-- CTRL : listDTO

deactivate CTRL

@enduml