@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam sequenceMessageAlign center

    CustomerManager -> System: Asks to start or close a phase of a job opening

    Activate CustomerManager

    Activate System

    System --> CustomerManager: Shows all Job Openings that have started but haven't closed.

    Deactivate System

    CustomerManager -> System: Chooses one

    Activate System

    System --> CustomerManager: Shows all the phases and their status

    System --> CustomerManager: Shows the phase that will be closed and/or started ( Depends which phase is currently open )

    System --> CustomerManager: Asks for the CustomerManager's confirmation of that action

    alt Confirmation is given

        CustomerManager -> System: Yes

        System --> CustomerManager: Shows confirmation message

    else Confirmation is not given

            CustomerManager -> System: No

            System --> CustomerManager: Goes back to the main menu

    end


@enduml