@startuml US2002_SSD
autonumber

actor "Operator" as USER
participant "System" as SYS

activate USER

USER -> SYS : asks to register an application
activate SYS

SYS --> USER : asks for the shared folder where the files used for the application are
deactivate SYS

USER -> SYS : selects the shared folder
activate SYS

SYS --> USER : shows operation success
deactivate SYS


'SYS --> USER : imports the information of the given files
'deactivate SYS

'USER -> SYS : selects the candidate's email
'activate SYS

'SYS --> USER : asks the candidate's email
'deactivate SYS
'
'USER -> SYS : selects the candidate's email
'activate SYS

'alt if the candidate doesn't exist
'
'SYS --> USER : import the candidate information from the files and register the candidate
''activate SYS
'deactivate SYS
'
'end alt

'SYS --> USER : asks for the job opening
'deactivate SYS
'
'USER -> SYS : selects the job opening
'activate SYS


'SYS --> USER : imports the information of the given files and register the application
'activate SYS
'
'deactivate SYS

'USER -> SYS : selects the job opening
'activate SYS
'
'
'SYS --> USER : register the application
'deactivate SYS

deactivate USER

@enduml