@startuml US1005_partial_convert_job_opening_list_to_DTO
'https://plantuml.com/sequence-diagram

title [US1005 - Partial SD] Convert Application List to DTO

participant "<<application>>\n:ListJobOpeningApplicationsController" as CTRL
participant "<<service>>\n:ApplicationMapper" as AppMapper
participant "<<domain>>\n:Application" as App
participant "<<application>>\nList<ApplicationDTO>" as DTOList
participant "<<application>>\nApplicationDTO" as DTO


-> CTRL : toDTO(applicationList)

activate CTRL

    CTRL -> AppMapper : convertToDTO(applicationList)
    activate AppMapper

        AppMapper -> DTOList : create()
        activate DTOList
        deactivate DTOList

        loop For all the applications in the list

            AppMapper -> App : requirementAnswer()
            activate App
            deactivate App

            AppMapper -> App : requirementResult()
            activate App
            deactivate App

            AppMapper -> App : file()
            activate App
            deactivate App

            AppMapper -> App : email()
            activate App
            deactivate App

            AppMapper -> App : applicationDate()
            activate App
            deactivate App

            AppMapper -> App : applicationStatus()
            activate App
            deactivate App

            AppMapper -> App : candidateName()
            activate App
            deactivate App

            AppMapper -> App : phoneNumber()
            activate App
            deactivate App

            AppMapper -> App : interview()
            activate App
            deactivate App

            AppMapper -> App : schedule()
            activate App
            deactivate App

            AppMapper -> App : interviewResult()
            activate App
            deactivate App

            AppMapper -> App : interviewGrade()
            activate App
            deactivate App

            AppMapper -> App : justification()
            activate App
            deactivate App

            AppMapper -> App : interviewAnswer()
            activate App
            deactivate App

            AppMapper -> DTO : create(requirementAnswer, requirementResult, file, email,\n applicationDate, applicationStatus, candidateName, phoneNumber,\n interview, schedule, interviewResult, interviewGrade, justification, interviewAnswer)
            activate DTO
            deactivate DTO

            AppMapper -> DTOList : add(applicationDTO)
            activate DTOList
            deactivate DTOList

        end loop

        AppMapper --> CTRL

    deactivate AppMapper

<-- CTRL : listDTO

deactivate CTRL

@enduml