@startuml US3001_SSD

title US3001 System Sequence Diagram

autonumber

actor "Candidate" as CAND
participant "System\n(Candidate App)" as SYS
participant "Follow Up Server" as SERVER

activate SYS

    activate CAND

        CAND -> SYS : authenticates

        SYS -> SERVER : establishes TCP connection

        activate SERVER

        SYS -> SERVER : authenticate user

            loop Every minute

                SYS -> SERVER : requests all unseen candidate's notifications

                SERVER --> SYS : candidate's notifications

            end

        deactivate SERVER

        CAND -> SYS : asks for notifications

        SYS --> CAND : shows notifications

    deactivate SYS

deactivate CAND

@enduml