@startuml US2001_SSD
autonumber

actor "Operator" as OP
participant "System" as SYS

activate OP

OP -> SYS : asks to generate a new requirements specification file

activate SYS

activate SYS

SYS --> OP : confirms the successful exportation of the file
deactivate SYS


deactivate OP

@enduml