@startuml US1010_Phase_State_Diagram
'https://plantuml.com/state-diagram

title US1010 Phase State Diagram

scale 350 width

state PLANNED {
}

state ON_GOING {
}

state CONCLUDED {
}

[*] --> PLANNED : Phase was just created \nand is neither open or closed
PLANNED --> ON_GOING : Activity important to that \ncertain phase is happening
ON_GOING --> CONCLUDED : All activity important to that \ncertain phase has concluded

@enduml