@startuml US3001_SSD

title US3001 System Sequence Diagram

autonumber

actor "CustomerManager" as C
participant "System\n(Customer App)" as SYS
participant "Follow Up Server" as SERVER

SERVER --> SYS : sends notification
activate SERVER
note right
every time an application
changes state
end note

activate SYS
deactivate SERVER

activate C
C -> SYS : asks to see notifications

SYS -> SERVER : establishes TCP connection
activate SERVER
SYS -> SERVER : requests candidate's notifications

SERVER --> SYS : customer's notifications
deactivate SERVER

SYS --> C : shows notifications
deactivate SYS
deactivate C

@enduml